#ifndef ERRORS_H
#define ERRORS_H 
#include <stdio.h>
#define COMPILED_SUCCESS 0
#define FUNCTION_COMPILED_SUCCESS 0

#define ERROR_BAD_ARGUMENT_COUNT 1
#define ERROR_BAD_FILE 2
#define ERROR_BAD_MAGIC_NUMBER 3
#define ERROR_BAD_COMMENT_LINE 4
#define ERROR_BAD_DIMENSIONS 5
#define ERROR_BAD_MAX_GRAY_VALUE 6
#define ERROR_IMAGE_MALLOC_FAILED 7
#define ERROR_BAD_DATA_READ 8
#define ERROR_OUTPUT_FAILED 9
#define ERROR_BAD_LAYOUT 10
#define ERROR_MISCELLANEOUS 100
#define ERROR_UNKNOWN 12

#define NUM_ERROR_STATUS 13

void ErrorExit(int errorCode, char *errStringInsert);

#endif 